---
- hosts: localhost
  vars:
      vcenter_hostname: 192.168.1.40
      vcenter_username: root
      vcenter_password: root
      datacenter_name: local
      appliance_name: vCenter-test1
  tasks:
      - import_role:
            name: vcenter-instance
        vars:
            vcenter_instance:
                installation:
                    from: iso  # use 'datastore' do reimport an instance from the datastore
                appliance:  # the vcenter appliance
                    name: "{{ appliance_name }}"
                    hostname: 192.168.1.92
                network:  # IP Configuration of the vcenter
                    address: 192.168.1.92
                    prefix: 24
                    gateway: 192.168.1.1
      - name: Create a snapshot
        vmware_guest_snapshot:
            hostname: "{{ vcenter_hostname }}"
            username: "{{ vcenter_username }}"
            password: "{{ vcenter_password }}"
            name: "{{ appliance_name }}"
            datacenter: "{{ datacenter_name }}"
            folder: "/vm"
            state: present
            snapshot_name: first-boot
            memory_dump: true
            description: Just after the deployment
