---
- hosts: localhost
  tasks:
    - import_role:
        name: vcenter-instance
      vars:
        vcenter_instance_installation_from: 'iso'
        vcenter_instance_network_address: '{{ vcsa_ip }}'
        vcenter_instance_network_prefix: 24
        vcenter_instance_network_gateway: 192.168.123.1
        vcenter_instance_network_dns: 192.168.123.1
        vcenter_instance_network_hostname: vcenter.test
        vcenter_instance_esxi_hostname: '{{ hostvars["esxi-vcenter"].ansible_host }}'
        vcenter_instance_esxi_username: root
        vcenter_instance_esxi_password: '!234AaAa56'
