- name: Mount point
  file:
    name: mount
    state: directory
- name: Prepare the vCSA_on_ESXi.json
  template:
    src: vCSA_on_ESXi.json.j2
    dest: /tmp/vCSA_on_ESXi.json

- block:
    - name: Mount DVD read-only
      command: "mount -t iso9660 {{ vcenter_instance_installation_iso_path }} {{ vcenter_instance_installation_iso_mount_point }}"
      become: true
    - name: "Start the deployment of vCSA, you can follow the log: /tmp/vcsa.log"
      shell: "./vcsa-deploy install -v --accept-eula --no-ssl-certificate-verification --acknowledge-ceip /tmp/vCSA_on_ESXi.json > /tmp/vcsa.log 2>&1"
      args:
        chdir: "{{ vcenter_instance_installation_iso_mount_point }}/vcsa-cli-installer/lin64"
        #    creates: "/tmp/vcsa.log"
  always:
    - name: Umount the DVD
      command: "umount {{ vcenter_instance_installation_iso_mount_point }}"
      become: true
      when: vcenter_instance_installation_auto_umount_iso
