- name: Mount point
  file:
    name: mount
    state: directory
- name: Prepare the vCSA_on_ESXi.json
  template:
    src: vCSA_on_ESXi.json.j2
    dest: /tmp/vCSA_on_ESXi.json

- block:
    - name: Mount DVD read-only
      mount:
        path: mount
        src: '{{ vcenter_instance_VCSA_iso }}'
        fstype: iso9660
        opts: loop,ro
        state: mounted
      become: true
    - name: "Start the deployment of vCSA, you can follow the log: {{ playbook_dir }}/vcsa.log"
      shell: "./vcsa-deploy install -v --accept-eula --no-ssl-certificate-verification --acknowledge-ceip /tmp/vCSA_on_ESXi.json > {{ playbook_dir }}/vcsa.log 2>&1"
      args:
        chdir: "{{ playbook_dir }}/mount/vcsa-cli-installer/lin64"
        creates: "/tmp/vcsa.log"
  always:
    - name: Umount the DVD
      mount:
        path: mount
        state: unmounted
      become: true
