---
- vmware_guest_info:
    hostname: "{{ vcenter_instance_esxi_hostname }}"
    username: "{{ vcenter_instance_esxi_username }}"
    password: "{{ vcenter_instance_esxi_password }}"
    port: "{{ vcenter_instance_esxi_port }}"
    validate_certs: "{{ vcenter_instance_esxi_validate_certs }}"
    name: "{{ vcenter_instance_appliance_name }}"
    datacenter: "{{ vcenter_instance_esxi_datacenter }}"
  register: lookup_result
  failed_when: false
- debug: var=lookup_result
- when: lookup_result.instance is not defined
  block:
  - include_tasks: restore_vsphere.yaml
    when: vcenter_instance_installation_from == "datastore"
  - include_tasks: create_vsphere.yaml
    when: vcenter_instance_installation_from == "iso"
